# Generated by Django 4.1.4 on 2022-12-30 08:33

from django.db import migrations, models
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_wallpaper_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallpaper",
            name="image",
            field=models.ImageField(
                default=django.utils.timezone.now,
                max_length=70,
                upload_to=main.models.category_dir_file,
            ),
            preserve_default=False,
        ),
    ]
